version: "3.8"
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    environment:
      BIND-ADDRESS: 0.0.0.0
      API_MYSQL_USER: demo_u
      API_MYSQL_PASSWORD: demo_pw
      API_MYSQL_HOST: mysql
      API_MYSQL_DATABASE: demo_db
    ports:
      - 8080:8080
    links:
      - mysql
    volumes:
      - ./api:/go/src/api

  mysql:
    container_name: mysql
    build: ./docker/database/
    hostname: mysql
    platform: linux/amd64
    environment:
      BIND-ADDRESS: 0.0.0.0
    ports:
      - "3306:3306"
  
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - "api"
    links:
      - api
    volumes:
      - ./client:/client